depot/config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
 controller :sessions do
 get 'login' => :new
 post 'login' => :create
 delete 'logout' => :destroy
end

  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end
  root 'store#index', as: 'store'

end

depot/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
with:
%r{\.(gif|jpg|png)\Z}i,
message: 'must be a URL for GIF, JPG or PNG image.'
}
def self.latest
Product.order(:updated_at).last
end



private
# ensure that there are no line items referencing this product
def ensure_not_referenced_by_any_line_item
  if line_items.empty?
  return true
  else
    errors.add(:base, 'Line Items present')
    return false
  end
 end


end

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pragprog Books Online Store</title>
<%= stylesheet_link_tag "application", media:"all","data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

</head>
<body class="<%= controller.controller_name %>">
<div id="banner">
<%= image_tag("logo.jpeg") %>
<%= @page_title || "Pragmatic Bookshelf" %>
</div>
<div id="columns">
<div id="side">
<div id="cart">
	<% if @cart %>
    <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
    <%= render @cart %>
    <% end %>
    <% end %>

</div>

<ul>
<li><a href="http://www....">Home</a></li>
<li><a href="http://www..../faq">Questions</a></li>
<li><a href="http://www..../news">News</a></li>
<li><a href="http://www..../contact">Contact</a></li>
<li><%=Time.now.asctime%></li>
</ul>
<% if session[:user_id] %>
<ul>
	<li><%= link_to 'Orders',orders_path%></li>
	<li><%= link_to 'Products', products_path %></li>
	<li><%= link_to 'Users',users_path%></li>
</ul>
<%= button_to 'Logout', logout_path, method: :delete %>
<% end %>
</div>
<div id="main">
<%= yield %>
</div>
</div>
</body>
</html>